# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91bc0dffd253712311865672f993d55e618c4d61fb07bc69dbd807f4c871d6e35a085729a276a65b665af2a28c395415a96ab66b8a779043411a6322a6beaefa

test:
  secret_key_base: 6ad35f874439e863fbf6d35f67e470eb1c354177c194cb53f3de4d1bd0e28cc30e713142733ea37f86a4af8b31c5fda5cf20653b1dee76220ffdb40533347657

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
